---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
cells: 
  cRfkbWLEO0E985_3oK6v-2:
    link:
      url: "	http://192.168.20.25:12080/home"
  cRfkbWLEO0E985_3oK6v-3:
    link:
      url: "https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/src/README.md"
